// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPrePhk9JKlXWQkR8DUfrG_Tv8-H5mIFA',
    appId: '1:911882123820:web:007c598cdfc55721b86f89',
    messagingSenderId: '911882123820',
    projectId: 'farmfix-4afbd',
    authDomain: 'farmfix-4afbd.firebaseapp.com',
    storageBucket: 'farmfix-4afbd.firebasestorage.app',
    measurementId: 'G-SWSMNQJ19M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZfv6LkYiSpJrdUsKzg1s2ZEAuKn9vt_4',
    appId: '1:911882123820:android:d331daf0d3b490b2b86f89',
    messagingSenderId: '911882123820',
    projectId: 'farmfix-4afbd',
    storageBucket: 'farmfix-4afbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA__kEKqfJ0cyneR8MWMH3LLa4q10ij52o',
    appId: '1:911882123820:ios:74574e582f4839f7b86f89',
    messagingSenderId: '911882123820',
    projectId: 'farmfix-4afbd',
    storageBucket: 'farmfix-4afbd.firebasestorage.app',
    iosBundleId: 'com.example.farmfix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA__kEKqfJ0cyneR8MWMH3LLa4q10ij52o',
    appId: '1:911882123820:ios:74574e582f4839f7b86f89',
    messagingSenderId: '911882123820',
    projectId: 'farmfix-4afbd',
    storageBucket: 'farmfix-4afbd.firebasestorage.app',
    iosBundleId: 'com.example.farmfix',
  );
}
